[package]
name = "egomoose/rbx-wallstick"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
private = true

[place]
shared-packages = "game.ReplicatedStorage.SharedPackages"

[dependencies]
Trove = "sleitnick/trove@1.5.0"
TypedRemote = "sleitnick/typed-remote@0.2.0"
RaycastHelper = "egomoose/raycast-helper@3.0.0"
CharacterSounds = "egomoose/character-sounds@0.2.1"
CharacterAnimate = "egomoose/character-animate@0.0.3"

[server-dependencies]
PlayerModule = "upliftgames/playermodule@664.0.6640713"